### ISSUE TITLE
Support for shields.io mimetypes other than SVG

### ISSUE THREAD

**Issue by budziq** [jaemk/badge-cache#2]
Currently there is an implicit assumption about SVG being the requested mimetype which may nat always be true for some badge-cache clients.
From shields.io main page
> We support .svg, .json, .png and a few others, but use them responsibly.

This has extremely low priority as most clients will want the default SVG format but you may want to consider this for the sake of completeness.

**Comment by jaemk** [comment]
Thanks, it's certainly something that should be addressed. I noticed their comment on supporting different formats, but I wasn't able to figure out how they're accessed. Is it one of the query params they accept?

**Comment by budziq** [comment]
Nope just replace the ".svg" with one of the formats like https://img.shields.io/crates/v/rustc-serialize.svg -> https://img.shields.io/crates/v/rustc-serialize.png

**Comment by jaemk** [comment]
Not sure how I missed that! Adding in support for this shouldn't be too hard then. We can default to `.svg` when no file format is specified, and then check against supported formats if it's present

**Comment by budziq** [comment]
Their "docs" are not really obvious on that ;)
Also they default to '.svg' when no type is given. I guess that th best
strategy would be not to strip anything from the name obtained via route
and pass it straight to requwest without adding '.svg'.

The only drawback is that "crate" and "crate.svg" would be distinct cache
entries but this is a negligible cost.

**Comment by jaemk** [comment]
Alright, I just updated a bunch of stuff. All of shields.io's supported file types should work now and there's an in-program cache to invalidate any items older than a specified lifespan in case the cron job that clears out files fails for some reason. I haven't done too much testing on it, so it's not live yet, but you can pull in the changes to check it out. The codes also pretty messy, I was just hack&slashing to get it working.

**Comment by budziq** [comment]
Excellent :)! I haven't gone into the implementation details (and did not
check the actual caching logic) but the server works great locally with
rust-cookbook.

I would just add the "expires" headers and make the changes live. Also I
don't think the cache duration needs to be as short as 1h crates are not
really that dynamic beasts ;)

**Comment by jaemk** [comment]
Alright, `Expires` header is added! I left the cache duration as 1hr just for those who happen to hit the cache right before it refreshes. I can extend it if it looks like I'm getting overwhelmed with traffic.

see commits 14eb71e & 86f86ca
